services:
  redis_mq:
    image: redis:alpine
    restart: always

  web_api:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - redis_mq
    volumes:
      - ./data:/app/data

  celery_worker:
    build: .
    command: celery -A worker.celery_app worker --loglevel=info
    depends_on:
      - redis_mq
    volumes:
      - ./data:/app/data